name: "Create venv"
description: "Create a temporary venv"
inputs:
  python-command:
    description: "The Python to use for creating the environment"
    required: false
    default: "python"
outputs:
  venv_path:
    description: "The path to the virtual environment directory, not including the bin or scripts directory."
    value: ${{ steps.create-venv.outputs.temp-venv-path }}
  python_executable:
    description: "The path to the Python executable in the virtual environment directory."
    value: ${{ steps.create-venv.outputs.temp-python-executable }}
runs:
  using: "composite"
  steps:
    - name: Create venv
      id: create-venv
      shell: sh
      run: |
        ${{ inputs.python-command }} "${GITHUB_ACTION_PATH}/create_temporary_venv.py"
    - uses: ${{ env.GITHUB_ACTION_PATH }}/../activate-venv
      with:
        directories: '[${{ toJSON(steps.create-venv.outputs.temp-venv-path) }}]'
    - name: Update pip
      shell: sh
      run: |
        "${{ steps.create-venv.outputs.temp-python-executable }}" -m pip install --upgrade pip
