name: "Activate virtual environment"
description: 'Activate the a virtual environment for future steps.'
inputs:
  directories:
    description: "A list of directories to attempt to activate, terminates on the first present directory.  Uses JSON format."
    required: true
    default: '["venv/", ".venv/"]'
#outputs:
#  virtual-env:
#    description: "The VIRTUAL_ENV environment value."
#    value:
#  virtual-env-bin:
#    description: "The path to the virtual environment directory containing the executables."
#    value:
runs:
  using: "composite"
  steps:
    - name: Activate virtual environment
      shell: sh
      env:
        INPUT_DIRECTORIES: ${{ inputs.directories }}
      run: |
        python "${GITHUB_ACTION_PATH}/activate-venv/activate_venv.py"
