name: "Poetry"
description: 'Install Poetry (Python packaging and dependency manager) and run `poetry install`'
inputs:
  poetry-command:
    description: "Poetry command to run. Does install by default."
    required: false
    default: 'install'
runs:
  using: "composite"
  steps:
    - name: Confirm Python and Pip are installed
      shell: bash
      run: |
        PYTHON_INSTALLED=0
        PIP_INSTALLED=0
        command -v python >/dev/null 2>&1 && { PYTHON_INSTALLED=1; }
        command -v python3 >/dev/null 2>&1 && { PYTHON_INSTALLED=1; }
        command -v pip >/dev/null 2>&1 && { PIP_INSTALLED=1; }
        if [ $PYTHON_INSTALLED == 0 ]
        then
          echo "Python or python3 command not found - please ensure Python is installed and try again"
          exit 1
        fi
        if [ $PIP_INSTALLED == 0 ]
        then
          echo "Pip command not found - please ensure python pip is installed and try again"
          exit 1
        fi

    - uses: Chia-Network/actions/create-venv@main
      id: create-venv

    - name: Install Poetry
      shell: bash
      run: |
        ${{ steps.create-venv.outputs.temp-python-executable }} -m pip install poetry

    - name: Run Poetry command (Linux)
      shell: bash
      run: |
        ${{ steps.create-venv.outputs.temp-python-executable }} -m poetry ${{ inputs.poetry-command }}
