name: "Clean Workspace"
description: "Cleans the current workspace before checking out code, to ensure a clean slate"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        sudo rm -rf * || rm -rf * || true
        sudo rm -rf .* || rm -rf .* || true
        sudo rm -rf $HOME/.npm || true
      shell: sh
