name: "Clean Workspace"
description: "Cleans the current workspace before checking out code, to ensure a clean slate"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        # Remove all files whose name does NOT start with '.'
        sudo rm -rf * || rm -rf * || true
        # Remove all files whose name starts with '.'
        sudo find . -name . -o -prune -exec rm -rf -- {} + || true
      shell: sh
