name: "Setup Python"
description: 'Set up a specific version of Python and add the command-line tools to the PATH.'
# Inputs match the upstream setup-python action
# Not all of them are necessarily supported for the M1 or ARM64 linux versions
inputs:
  python-version:
    description: "Version range or exact version of a Python version to use, using SemVer's version range syntax."
    required: true
    default: '3.x'
  cache:
    description: 'Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.'
    required: false
  architecture:
    description: 'The target architecture (x86, x64) of the Python interpreter.'
    required: false
  token:
    description: Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
    required: false
    default: ${{ github.token }}
  cache-dependency-path:
    required: false
    description: 'Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies.'
outputs:
  python-version:
    description: "The installed python version. Useful when given a version range as input."
  cache-hit:
    description: 'A boolean value to indicate a cache entry was found'
runs:
  using: "composite"
  steps:
    - name: Call upstream setup-python action
      uses: actions/setup-python@v3
      # Runner arch doesn't work until we have native m1 runner software, since it runs with an arch flag on the host
      # if: runner.arch == 'X64'
      if: ${{ !startsWith('m1-', runner.name) }}
      with:
        python-version: ${{ inputs.python-version }}
        architecture: ${{ inputs.architecture }}
        cache: ${{ inputs.cache }}
        token: ${{ inputs.token }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
    - name: Setup Python on ARM64 MacOS
      # Runner arch doesn't work until we have native m1 runner software, since it runs with an arch flag on the host
      # if: runner.arch == 'ARM64' && runner.os == 'macOS'
      if: ${{ startsWith('m1-', runner.name) }}
      shell: sh
      run: |
        arch -arm64 brew install python@${{ inputs.python-version }}
        PY_PREFIX=$(arch -arm64 brew prefix python@${{ inputs.python-version }})
        echo "PATH=$PY_PREFIX/bin:$PATH" >> $GITHUB_ENV
