name: test-setup-python

on:
  push:
    branches:
    - main
    tags:
    - '**'
  pull_request:
    branches:
    - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/long_lived/')) && github.sha || '' }}
  cancel-in-progress: true

defaults:
  run:
    shell:
      bash

jobs:
  test:
    name: ${{ matrix.os.name }} ${{ matrix.arch.name }} ${{ matrix.python.name }}
    runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix] }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: macOS
            matrix: macos
            runs-on:
              arm: [macOS, ARM64]
              intel: [macos-latest]
          - name: Ubuntu
            matrix: ubuntu
            runs-on:
              arm: [Linux, ARM64]
              intel: [ubuntu-latest]
          - name: Windows
            matrix: windows
            runs-on:
              intel: [windows-latest]
        python:
          - name: '3.7'
            action: '3.7'
            check: '3.7'
            patch-specified: false
            matrix: 'py3.7'
          - name: '3.8'
            action: '3.8'
            check: '3.8'
            patch-specified: false
            matrix: 'py3.8'
          - name: '3.9'
            action: '3.9'
            check: '3.9'
            patch-specified: false
            matrix: 'py3.9'
          - name: '3.10'
            action: '3.10'
            check: '3.10'
            patch-specified: false
            matrix: 'py3.10'
          - name: '3.10.8'
            action: '3.10.8'
            check: '3.10.8'
            patch-specified: true
            matrix: 'py3.10.8'
          - name: '3.11'
            action: '3.11'
            check: '3.11'
            patch-specified: false
            matrix: 'py3.11'
          - name: '3.12'
            action: '3.12'
            check: '3.12'
            patch-specified: false
            matrix: 'py3.12'
        arch:
          - name: ARM
            matrix: arm
          - name: Intel
            matrix: intel
        exclude:
          # Only partial entries are required here by GitHub Actions so generally I
          # only specify the `matrix:` entry.  The super linter complains so for now
          # all entries are included to avoid that.  Reported at
          # https://github.com/rhysd/actionlint/issues/249
          - os:
              name: Windows
              matrix: windows
              runs-on:
                intel: [windows-latest]
            arch:
              name: ARM
              matrix: arm
          - os:
              name: macOS
              matrix: macos
              runs-on:
                arm: [macOS, ARM64]
                intel: [macos-latest]
            python:
              name: '3.7'
              action: '3.7'
              check: '3.7'
              matrix: 'py3.7'
            arch:
              name: ARM
              matrix: arm

    steps:
    - uses: actions/checkout@v3

    - name: Run the action
      uses: ./setup-python/
      id: run-the-action
      with:
        python-version: ${{ matrix.python.action }}

    - name: Check Python version
      env:
        PYTHON_CHECK: ${{ matrix.python.check }}
      run: |
        python ./setup-python/test_check_version.py

    - name: Make sure pre-release version adjustment made if appropriate
      env:
        VALUE: ${{ matrix.python.patch-specified && ( steps.run-the-action.outputs.python-version-string == matrix.python.action ) || contains(steps.run-the-action.outputs.python-version-string, '.0-alpha') }}
      run: |
        [ "${VALUE}" = 'true' ]
